# Generated by Django 3.1.4 on 2021-01-03 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('spotify_id', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('popularity', models.IntegerField()),
                ('uri', models.CharField(max_length=100)),
                ('related', models.ManyToManyField(related_name='_artist_related_+', to='splatify.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('populated', models.BooleanField(default=False)),
                ('account', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TopArtist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affinity', models.IntegerField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='splatify.artist')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='splatify.profile')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedArtist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affinity', models.IntegerField()),
                ('artist1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='root_artist', to='splatify.artist')),
                ('artist2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_artist', to='splatify.artist')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='fave_artists',
            field=models.ManyToManyField(through='splatify.TopArtist', to='splatify.Artist'),
        ),
    ]
