# Generated by Django 3.1.4 on 2021-01-04 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splatify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relatedartist',
            old_name='artist1',
            new_name='root_artist',
        ),
    ]
